[versions]
agp = "8.9.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
kotlin = "2.0.21"
coreKtx = "1.10.1"
leanback = "1.2.0-alpha02"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { module = "androidx.leanback:leanback", version.ref = "leanback" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

